# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.warning.mode = all
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version   = 26.2
loader_version      = 0.19.3
java_version        = 25
loom_version        = 1.17-SNAPSHOT

# Mod Properties
mod_version         = 2.7.2
maven_group         = dev.hephaestus
archives_base_name  = atmosfera

# Dependencies
fabric_api_version   = 0.152.1+26.2
modmenu_version      = 18.0.0-alpha.8
clothconfig_version  = 26.1.154

loader_version_range = >=0.18.5
game_version_range   = >=26.2
game_version_list    = 26.2

# Publishing
modrinth_id                      = 28G1xpgF
modrinth_dependencies            = fabric-api, cloth-config
modrinth_optional_dependencies   = modmenu
curseforge_id                    = 338456
curseforge_dependencies          = fabric-api, cloth-config
curseforge_optional_dependencies = modmenu
