# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.warning.mode = all
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version   = 1.19
yarn_mappings       = 1.19+build.4
loader_version      = 0.18.4
pack_format         = 9
java_version        = 17
loom_version        = 1.15-SNAPSHOT

# Mod Properties
mod_version         = 2.7.0
maven_group         = dev.hephaestus
archives_base_name  = atmosfera

# Dependencies
fabric_version      = 0.56.1+1.19
modmenu_version     = 4.0.0
clothconfig_version = 7.0.72

loader_version_range = >=0.15.0
game_version_range   = >=1.19 <=1.19.2
game_version_list    = 1.19, 1.19.1, 1.19.2

# Publishing
modrinth_id                      = 28G1xpgF
modrinth_dependencies            = fabric-api, cloth-config
modrinth_optional_dependencies   = modmenu
curseforge_id                    = 338456
curseforge_dependencies          = fabric-api, cloth-config
curseforge_optional_dependencies = modmenu
