# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.warning.mode = all
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# Check on https://fabricmc.net/develop/
minecraft_version   = 1.21.6
yarn_mappings       = 1.21.6+build.1
loader_version      = 0.18.2
pack_format         = 64
java_version        = 21
loom_version        = 1.14-SNAPSHOT

# Mod Properties
mod_version         = 2.5.3
maven_group         = dev.hephaestus
archives_base_name  = atmosfera

# Dependencies
fabric_version       = 0.127.1+1.21.6
modmenu_version      = 15.0.0-beta.2
clothconfig_version  = 19.0.147

loader_version_range = >=0.15.0
game_version_range   = >=1.21.6 <1.21.9
game_version_list    = 1.21.6, 1.21.7, 1.21.8

# Publishing
modrinth_id                      = 28G1xpgF
modrinth_dependencies            = fabric-api, cloth-config
modrinth_optional_dependencies   = modmenu
curseforge_id                    = 338456
curseforge_dependencies          = fabric-api, cloth-config
curseforge_optional_dependencies = modmenu
