pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        exclusiveContent {
            forRepository {
                maven {
                    url = 'https://maven.maxhenkel.de/repository/public'
                }
            }
            filter {
                includeGroupAndSubgroups 'de.maxhenkel'
            }
        }
    }
}
